backend:
  name: git-gateway
  branch: main 

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "gallery"
    label: "Gallery"
    folder: "/images"
    create: false
    fields:
      - { name: "src", label: "Image", widget: "image" }
      - { name: "alt", label: "Alt Text", widget: "string" }
      - { name: "dataName", label: "Data Name", widget: "string" }
