backend:
  name: git-gateway
  branch: main 

media_folder: "src/images"

collections:
  - name: articles
    label: Articles
    folder: _articles
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: body, label: Body, widget: markdown }